jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Grant execute permission for script
      run: chmod +x ./startup-for-github-actions.sh
    - name: Run startup.sh
      run: ./startup-for-github-actions.sh
