name: Notebook Diff Check
on:
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run startup-for-github-actions.sh
      run: ./startup-for-github-actions.sh
