name: reviewdog-javacript

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
    - name: Check out code.
      uses: actions/checkout@v4

    - name: Set up reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install
      run: npm install

    - name: Run eslint with reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        eslint_flags: 'scripts/*.{js,jsx,ts,tsx}'
        github_token: ${{ secrets.ACTIONS_TOKEN }}
        continue-on-error: true
